### ISSUE TITLE
Getting error  "couldnt get tmp file after conversion" when trying to convert raw format to wav format

### ISSUE THREAD

**Issue by janvda** [johanneskropf/node-red-contrib-sox-utils#2]
When trying to convert raw format to wav file using the sox-convert node I am getting error:

```
"couldnt get tmp file after conversion"
```

The properties of the sox-convert node:
![image](https://user-images.githubusercontent.com/17238398/98031161-6785d200-1e12-11eb-8ab1-cae691b7838d.png)

The input for the sox-convert node =
![image](https://user-images.githubusercontent.com/17238398/98031354-a74cb980-1e12-11eb-96e8-4ef77fd2890b.png)

As you can see I have set `msg.format="raw"`

**Comment by johanneskropf** [comment]
Does it work if you set the node to output to a file? What is the output of the debug output? Do you see any messages on the second debug output about the conversion?
Edit:
I think I know the answer. The conversion will not work with raw audio as sox would need the audio to be accompanied by information about the bit rate etc as there are no headers in the raw audio buffer that would tell sox those informations about the audio.
Unfortunately the node right now doesn’t provide a way to enter this information together with the buffer.
Where does the raw audio come from? You could maybe use something like https://github.com/bartbutenaers/node-red-contrib-wav to add wav headers to your audio buffer before passing it to the conversion node.
You will always need to know things like Bitrate etc when working with raw audio as no Programm can guess those.

Johannes

**Comment by janvda** [comment]
Thanks for the fast response.
... this issue is not blocking for me... so there is no need to fix this for me.

I understand that the node doesn't support the conversion from the raw format,
but I think that sox is able to do that conversion if I consult the internet (e.g. https://stackoverflow.com/questions/2059014/converting-raw-audio-data-to-wav-with-scripting)

I also understand that you need to specify Bitrate, ... for the conversion, but all these things can be specified in the properties of the sox-convert node:

![image](https://user-images.githubusercontent.com/17238398/98084935-dbf55b00-1e7c-11eb-90e0-a97c67ebea04.png)

**Comment by johanneskropf** [comment]
Those are the settings for the output File.
Im working on a fix for the node right now. This will give you the possibility to provide the necessary information with the incoming payload for example with a change node like this:
![1F95F4C8-DB24-48E4-B563-90C8856A1535](https://user-images.githubusercontent.com/46578064/98089478-13670600-1e83-11eb-8b5e-13d39713a176.jpeg)

I will push it to the repository later today.

**Comment by johanneskropf** [comment]
Pushed fix to the repo as 0.2.6.

https://github.com/johanneskropf/node-red-contrib-sox-utils/commit/822e05c03b41bb6fb5fc2347947ca3cde95bc6ff

The right format to add the missing header information will be told either in the error or is also now described in the info panel for the convert node.
