### ISSUE TITLE
sox record stops after reporting ALSA problems: over-run / rate clipped X samples

### ISSUE THREAD

**Issue by janvda** [johanneskropf/node-red-contrib-sox-utils#4]
I have setup pulseaudio and sox record is using default device (= so is using pulseaudio).
FYI: To overcome the error in issue #3 I am using my branch : 
* https://github.com/janvda/node-red-contrib-sox-utils/tree/pulseaudio_support

When I run  sox record continuously with below options:
![image](https://user-images.githubusercontent.com/17238398/101377882-b069f400-38b2-11eb-86f2-32be5b516792.png)

then it is frequently stopping with following error/warning:

```
{
  payload: 'sox WARN alsa: over-run\n' +
    "sox FAIL sox: `default' I/O error: Operation not permitted\n",
  _msgid: '61d942a2.12b02c'
}
7 Dec 17:28:21 - [info] [debug:sox-record output2] 
{
  payload: 'sox WARN rate: rate clipped 2511 samples; decrease volume?\n' +
    'sox WARN dither: dither clipped 2224 samples; decrease volume?\n',
  _msgid: '61d942a2.12b02c'
}
```

**Comment by johanneskropf** [comment]
It could be some conflicts because even if you use default the command generated by my node will still be alsa default.
You could try changing this line:
https://github.com/johanneskropf/node-red-contrib-sox-utils/blob/6d63887063287d02a4d22a236398acfe5f261846/sox_record.js#L305
to:
```
node.argArr.push("pulseaudio",node.inputSource);
```
combined with choosing the default maybe this would work.
Unfortunately I have no experience at all with pulseaudio.

**Comment by johanneskropf** [comment]
Maybe the node could work with alsa and pulseaudio with something like this:
https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_as_a_minimal_unintrusive_dumb_pipe_to_ALSA
So you configure the pulseaudio sink to be the default audio device in alsa which in turn should make it show up in the node via arecord -l?

**Comment by janvda** [comment]
Thanks for the response.

Note that pulseaudio is working using my changes in branch https://github.com/janvda/node-red-contrib-sox-utils/tree/pulseaudio_support

It is only that after some time (not immediately) I am getting the above error.

**Comment by johanneskropf** [comment]
I still think this is due to some conflicts because it’s not generating the right command. I will implement something in the next few days that will show a text input field when arecord -l fails where you can manually input the devices.
This should enable you to then enter something like `-t pulseaudio default` or even a specific pulse device and would than also allow you to use something like jack.
I will tell you when I push it to the repo and it would be good if you could try it than.

**Comment by janvda** [comment]
wait with making any changes.
It is more or less working just using the default (so no need to specify any UI to allow to select the device).

I am trying to figure out the actual options that are set when sox record command becomes spawned by the node as I would like to reproduce the problem without node-red by directly calling the sox command from the command line.

**Comment by johanneskropf** [comment]
You can start recording with the node and than use `htop` or `top` in the terminal of the machine running nodered and you will see the sox process which should show the whole command.
I will change some stuff because I think it will be better to use `sox -d ...` instead of `sox -t alsa default...` which is what is used now by the node when default is selected.
The manual input setting will become an additional option in the source dropdown.

**Comment by janvda** [comment]
Thanks.

I managed to reproduce the problem by just running sox command with same options as is used in my node-red flow:

```
bash-5.0$ sox -q -t alsa default -L -e signed-integer -c 1 -r 44100 -b 16 -t raw - gain 0 > out1234

sox WARN alsa: over-run
sox FAIL sox: `default' I/O error: Operation not permitted
bash-5.0$ 
```

Note that it didn't immediately report this error.  
It ran for some time before reporting this error (FYI the size of `out1234 `= 7 Mb ).

**Comment by janvda** [comment]
> This should enable you to then enter something like `-t pulseaudio default` or even a specific pulse device and would than also allow you to use something like jack.

The problem with that solution is that the pulseaudio format handler is not installed by default

```
bash-5.0$ sox -q -t pulseaudio alsa_input.pci-0000_00_0e.0.analog-stereo -L -e signed-integer -c 1 -r 44100 -b 16 -t raw - gain 0 > out1234
sox FAIL formats: no handler for given file type `pulseaudio'
```
... and I can not install this as it is not available in the docker alpine image that my node-red docker image is using.

```
bash-5.0$ sudo apk add libsox-fmt-pulse
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libsox-fmt-pulse (missing):
    required by: world[libsox-fmt-pulse]
bash-5.0$ 
```
Following link specifies the available `libsox_fmt` packages for latest alpine linux distribution

* https://pkgs.alpinelinux.org/contents?page=2&file=libsox_fmt%2A&branch=edge

So you can see that `libsox_fmt_pulse` is missing.

**Comment by johanneskropf** [comment]
Can you pleas pull the repository and update with my master and try it, I just bumped it to 0.4.0 and added/changed three things:
+ similar to your work around an error getting devices doesnt block the node anymore
+ changed the default setting to the more general `-d`
+ added an option to the source dropdown to input a manual source, this reveals a text field where you can enter a source as per the sox documentation. (`-t alsa default`, `-d`, `-t alsa plughw:1,0`, `-t pulseaudio default` and so on, even a file path as a source like `/home/pi/test.wav` will work)

Further more you could try another workaround for your docker container as this of course complicates things:
Use an exec node in spawn mode with a [`parec`/`pacat` command](https://linux.die.net/man/1/pacat) and connect it to the sox node in the recently added record from input mode. That way you can use the native pulseaudio recording with all the fancy stuff from sox. 

Edit:
0.4.1 error getting output devices now shouldn’t block play node either and enable trying to play to system default

**Comment by johanneskropf** [comment]
Here is an example flow with arecord but this should work similarly with parec/pacat:
```
[{"id":"85f664e3.9b96e8","type":"sox-record","z":"1b5e73a9.1939fc","name":"","buttonStart":"msg","inputs":1,"inputSource":"fromInput","manualSource":"/home/pi/test.wav","inputEncoding":"signed-integer","inputChannels":1,"inputRate":16000,"inputBits":16,"byteOrder":"-L","encoding":"signed-integer","channels":1,"rate":16000,"bits":16,"gain":"0","lowpass":8000,"showDuration":false,"durationType":"forever","durationLength":0,"silenceDetection":"nothing","silenceDuration":"2.0","silenceThreshold":"2.0","outputFormat":"wav","manualPath":"test_arecord","debugOutput":true,"x":790,"y":1020,"wires":[["6b32a635.1d79f8"],["3239a7de.f453e"]]},{"id":"6b32a635.1d79f8","type":"debug","z":"1b5e73a9.1939fc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":990,"y":1020,"wires":[]},{"id":"86152c16.4052","type":"exec","z":"1b5e73a9.1939fc","command":"arecord -d 5 -c 1 -r 16000 -f S16_LE -t raw -","addpay":false,"append":"","useSpawn":"true","timer":"","oldrc":false,"name":"","x":490,"y":1040,"wires":[["85f664e3.9b96e8"],["1359ca9c.dc71bd"],["1359ca9c.dc71bd"]]},{"id":"1359ca9c.dc71bd","type":"debug","z":"1b5e73a9.1939fc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":790,"y":1060,"wires":[]},{"id":"91b5c6e6.e70b78","type":"inject","z":"1b5e73a9.1939fc","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":1040,"wires":[["86152c16.4052"]]},{"id":"3239a7de.f453e","type":"debug","z":"1b5e73a9.1939fc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":990,"y":1060,"wires":[]}]
```
The `parec` command would be something like this: `parec --rate 16000 --format s16le --channels 1 --raw`

**Comment by janvda** [comment]
Thanks for updating it.
Just tested it.

When using the default device:
![image](https://user-images.githubusercontent.com/17238398/101487886-1c099b00-395f-11eb-82a7-ce98ffd294c8.png)

It is logging following warning:
```
sox WARN alsa: can't encode 0-bit Unknown or not applicable
```

FIY the command I see in top is

```
sox -q -d -L -e signed-integer -c 1 -r 44100 -b 16 -t raw - gain 0
```

**Comment by janvda** [comment]
Also `parec` command, launched from command line is stopping after some time with error (see below).
So this issue can be closed as the problem is certainly not in your code.
Thanks a lot for your support.

```
bash-5.0$ parec -v --rate 16000 --format s16le --channels 1 --raw > out234
Opening a recording stream with sample specification 's16le 1ch 16000Hz' and channel map 'mono'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, fragsize=64000
Using sample spec 's16le 1ch 16000Hz', channel map 'mono'.
Connected to device alsa_input.pci-0000_00_0e.0.analog-stereo (index: 1, suspended: no).
Connection failure: Connection terminated      
Stream error: Connection terminated
bash-5.0$
```

**Comment by johanneskropf** [comment]
Anything that says warn can in most cases be safely ignored with sox. It should still work with this warning and should be nothing to worry about.
The pulseaudio problem on the other side looks to be a docker problem.
Am i right in that pulseaudio is accessing maped audio devices from outside the container?
It could be that the pulseaudio server running inside the docker container is loosing connection to the outside periodically for some reason. 
I dont think this is a problem related either to sox or pulseaudio but instead really a docker issue if even the native parec is failing.

**Comment by janvda** [comment]
> Anything that says warn can in most cases be safely ignored with sox. It should still work with this warning and should be nothing to worry about.

OK, that makes sense.

> I dont think this is a problem related either to sox or pulseaudio but instead really a docker issue if even the native parec is failing.

I agree that it is not related to sox.
In the mean time I have been one step further nailing down the problem:

I am also having the problem when running on the host machine (so no docker involvement) the following command:
`parec -v --rate 16000 --format s16le --channels 1 --raw > out234`

Running the command `journalctl | grep pulseaudio`  on the host also shows that pulseaudio is restarted every 90 sec due to timeout.  Still need to figure out how I can stop this restarting but that most likely is causing this.

```
Dec 08 15:41:11 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Start operation timed out. Terminating.
Dec 08 15:41:11 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Failed with result 'timeout'.
Dec 08 15:41:12 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Service RestartSec=100ms expired, scheduling restart.
Dec 08 15:41:12 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Scheduled restart job, restart counter is at 2.
Dec 08 15:41:12 nuc-jan.borsbeek pulseaudio[215262]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Dec 08 15:41:12 nuc-jan.borsbeek pulseaudio[215262]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
Dec 08 15:41:12 nuc-jan.borsbeek pulseaudio[215262]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
Dec 08 15:41:12 nuc-jan.borsbeek pulseaudio[215262]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Dec 08 15:41:12 nuc-jan.borsbeek pulseaudio[215262]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
Dec 08 15:42:42 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Start operation timed out. Terminating.
Dec 08 15:42:42 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Failed with result 'timeout'.
Dec 08 15:42:42 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Service RestartSec=100ms expired, scheduling restart.
Dec 08 15:42:42 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Scheduled restart job, restart counter is at 3.
Dec 08 15:42:42 nuc-jan.borsbeek pulseaudio[216711]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Dec 08 15:42:42 nuc-jan.borsbeek pulseaudio[216711]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
Dec 08 15:42:42 nuc-jan.borsbeek pulseaudio[216711]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
Dec 08 15:42:42 nuc-jan.borsbeek pulseaudio[216711]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Dec 08 15:42:42 nuc-jan.borsbeek pulseaudio[216711]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
Dec 08 15:44:12 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Start operation timed out. Terminating.
Dec 08 15:44:12 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Failed with result 'timeout'.
Dec 08 15:44:13 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Service RestartSec=100ms expired, scheduling restart.
Dec 08 15:44:13 nuc-jan.borsbeek systemd[3905274]: pulseaudio.service: Scheduled restart job, restart counter is at 4.
Dec 08 15:44:13 nuc-jan.borsbeek pulseaudio[218189]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Dec 08 15:44:13 nuc-jan.borsbeek pulseaudio[218189]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
Dec 08 15:44:13 nuc-jan.borsbeek pulseaudio[218189]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
Dec 08 15:44:13 nuc-jan.borsbeek pulseaudio[218189]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Dec 08 15:44:13 nuc-jan.borsbeek pulseaudio[218189]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
```

**Comment by johanneskropf** [comment]
Can I close this issue as the problem doesn’t seem to be related to the nodes?

**Comment by janvda** [comment]
yes, sure you can close it !
