### ISSUE TITLE
RFE - allow 'filename' to be passed in via msg.filename 

### ISSUE THREAD

**Issue by juggledad** [johanneskropf/node-red-contrib-sox-utils#5]
It would be nice if one could build the **filename** and pass it into 'sox-record'. The case I just hit is I want to try out node-red-contrib-personal-wake-word and need to record the wake word multiple times. If I could dynamically build the filename, this would be easier to do.

**Comment by johanneskropf** [comment]
Ill have a look at adding this functionality

**Comment by johanneskropf** [comment]
Closed as implemented for both record and convert see:
https://github.com/johanneskropf/node-red-contrib-sox-utils/commit/520e52a633d3197855bc103d6c4913f59738849f
