### ISSUE TITLE
raspberry pi 

### ISSUE THREAD

**Issue by mau2806** [johanneskropf/node-red-contrib-sox-utils#6]
[
    {
        "id": "8a5fd4d2.06cc78",
        "type": "tab",
        "label": "voice2json",
        "disabled": false,
        "info": ""
    },
    {
        "id": "a76c3e16.f7dba",
        "type": "sox-record",
        "z": "8a5fd4d2.06cc78",
        "name": "",
        "buttonStart": "msg",
        "inputs": 1,
        "inputSource": "default",
        "manualSource": "",
        "inputEncoding": "signed-integer",
        "inputChannels": 1,
        "inputRate": 16000,
        "inputBits": 16,
        "byteOrder": "-L",
        "encoding": "signed-integer",
        "channels": 1,
        "rate": 16000,
        "bits": 16,
        "gain": "0",
        "lowpass": 8000,
        "showDuration": false,
        "durationType": "forever",
        "durationLength": "0",
        "silenceDetection": "nothing",
        "silenceDuration": "2.0",
        "silenceThreshold": "2.0",
        "outputFormat": "stream",
        "manualPath": "",
        "debugOutput": false,
        "x": 460,
        "y": 140,
        "wires": [
            [],
            [
                "ddd44a5b.d980e8"
            ]
        ]
    },
    {
        "id": "ac291b08.9436a8",
        "type": "inject",
        "z": "8a5fd4d2.06cc78",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "start",
        "payloadType": "str",
        "x": 220,
        "y": 140,
        "wires": [
            [
                "a76c3e16.f7dba"
            ]
        ]
    },
    {
        "id": "49d18aaf.0ad954",
        "type": "inject",
        "z": "8a5fd4d2.06cc78",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "stop",
        "payloadType": "str",
        "x": 200,
        "y": 200,
        "wires": [
            [
                "a76c3e16.f7dba"
            ]
        ]
    },
    {
        "id": "ddd44a5b.d980e8",
        "type": "debug",
        "z": "8a5fd4d2.06cc78",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 800,
        "y": 180,
        "wires": []
    }
]

The flow generates debug outout:

2.5.2021, 08:24:12node: ddd44a5b.d980e8
msg.payload : string[8]
"starting"
2.5.2021, 08:24:12node: ddd44a5b.d980e8
msg.payload : string[51]
"sox FAIL sox: Buffer size `undefined' must be > 16↵"
2.5.2021, 08:24:12node: ddd44a5b.d980e8
msg.payload : string[8]
"complete"

/etc/asound contains:
sudo cat /etc/asound.conf
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
}

I tried to set the sox --buffer parameter but failed to implement it several ways but failed How can I work around getting this error?

NodeRed Version: 1.3.4

**Comment by johanneskropf** [comment]
You are using an old version, if you update to the newest version of node-red-contrib-sox-utils there is actually a buffer setting in the nodes config.
But im not sure will help you as this could also be a problem with your input device.

**Comment by mau2806** [comment]
I updated the node but there is no option for setting buffer in nodered node.
Inspecting the code I found the new variable and set it manually (just before: node.argArr.push("--buffer",node.buffer);)

diff sox_record.js.ori sox_record.js
315a316
>         node.buffer=20000;

With this setting my "sox-record" is running fine.

**Comment by johanneskropf** [comment]
So sorry I pushed the change to the js file but forgot about the html, I will push 0.5.2 to fix immediately ![1533F52D-C28B-48C6-B77B-FF12CBD8489A](https://user-images.githubusercontent.com/46578064/116809791-29a70380-ab40-11eb-997a-2ccb5971ca21.jpeg)

**Comment by johanneskropf** [comment]
Thanks for spotting this, I added the buffer argument in 0.5.1 but forgot to push the config change from my dev version. It should be fixed now in 0.5.2 and as soon as it shows up in the pallet you should be able to set the buffer in the config as above. You should be able to update with npm immediately.
So can you please update to 0.5.2 and check it works, I will close the issue than.
Best regards Johannes

**Comment by mau2806** [comment]
It's now working as you described. 
Great job! Thanks a lot! Have I nice sunday.

Markus
