### ISSUE TITLE
syntax for "manual source input" of sox-record node

### ISSUE THREAD

**Issue by mau2806** [johanneskropf/node-red-contrib-sox-utils#7]
Hi,
which syntax is needed to use the manual source input?
Using the sox-record node I want to switch to another microphone and want to specify it via the node parameter.
Which syntax is needed for that?

**Comment by johanneskropf** [comment]
this depends on which operating system you are running. on linux its:
```
-t alsa plughw:YourDevice
```
where your device is what is listed in `arecord -l` but if your on mac os its gonna be:
```
-t coreaudio YourDevice
```

**Comment by mau2806** [comment]
Thanks a lot. That works perfect.
